version: '3'

services:
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_MULTIPLE_DATABASES=sprinkling_db,sprinkling_test_db
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test123
      - MYSQL_ROOT_PASSWORD=test123
    ports:
      - "127.0.0.1:33306:3306"
    volumes:
      - ./initialize_databases.sh:/docker-entrypoint-initdb.d/initialize_mysql_multiple_databases.sh
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci --sql-mode=""
    healthcheck:
      test: '/usr/bin/mysql -P 3306 -h 127.0.0.1 --user=test --password="test123" --execute "SHOW DATABASES;"'
      interval: 3s
      timeout: 1s
      retries: 5
